[package]
name = "ecochain"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
tokio = { version = "1", features = ["full"] }
libp2p = "0.51"
serde = { version = "1.0", features = ["derive"] }
